# Generated by Django 2.2.5 on 2019-09-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/images', verbose_name='image'),
        ),
    ]
